### PR TITLE
Fix broken dependencies

### LINKED ISSUE #7: Can't build...
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':compile'.
> Could not resolve :CoFHCore:[1.7.10]3.0.0B9-40-dev.
  Required by:
      org.sidoh:reactor_simulator:0.1.0
   > Could not GET 'https://libraries.minecraft.net//CoFHCore/%5B1.7.10%5D3.0.0B9-40-dev/CoFHCore-%5B1.7.10%5D3.0.0B9-40-dev.pom'. Received status code 403 from server: Forbidden
   > Could not GET 'http://addons.cursecdn.com/files/2221/835/CoFHCore-%5B1.7.10%5D3.0.0B9-40-dev.xml'.
      > org.apache.http.client.ClientProtocolException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2 mins 2.996 secs

```

### PR DESCRIPTION
**Pull request by AlanGreene**
Update dependencies so gradle build completes successfully.
Resolves #7

### CODE REVIEW

**Comment by sidoh** [comment]
Thanks for looking into this.  Meant to do this a while ago, but didn't get around to it.

It seems like it's not compiling, even with these changes, though:

```
$ ./gradlew run
****************************
 Powered By MCP:
 http://modcoderpack.com/
  1 buildscript {
 Searge, ProfMobius, Fesh0r,
 R4wk, ZeuX, IngisKahn, bspkrs
 MCP Data version : unknown
****************************
:downloadClient SKIPPED
:downloadServer SKIPPED
:getVersionJson
:extractUserDev
:mergeJars SKIPPED
:applyBinPatches SKIPPED
:downloadMcpTools SKIPPED
:extractMcpData UP-TO-DATE
:genSrgs SKIPPED
:deobfBinJar SKIPPED
:compileApiJava UP-TO-DATE
:processApiResources UP-TO-DATE
:apiClasses UP-TO-DATE
:sourceMainJava UP-TO-DATE
:compileJava

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':compile'.
> Could not resolve li.cil.oc:OpenComputers:MC1.7.10-1.4.0.+.
  Required by:
      org.sidoh:reactor_simulator:0.1.0
   > Could not list versions using Ivy pattern 'http://addons-origin.cursecdn.com/files/2230/211/[module]-[revision].[ext]'.
      > Could not GET 'http://addons-origin.cursecdn.com/files/2230/211/'. Received status code 403 from server: Forbidden

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 22.578 secs
```

Anything obvious I'm missing?

**Comment by AlanGreene** [comment]
Odd, I'll take another look tonight.

**Comment by AlanGreene** [comment]
Looks like I had some cached dependencies, and the previously referenced version of OpenComputers is no longer available at that location.

I've relaxed the version range to accept 1.4.+ and that's working for me now. Alternatively I could change it to 1.4.9.+ if you'd rather lock it down a bit more.

Travis config seems to be wrong on the PR builds, it's looking for a Rakefile...

**Comment by sidoh** [comment]
Working for me! Thanks :)

Could you pull from master? I added a `.travis.yml`, and wanna make sure it builds in a clean environment as well.

**Comment by AlanGreene** [comment]
Hopefully that did the trick 😃

**Comment by sidoh** [comment]
Looks good. Thanks again!

**Comment by AlanGreene** [comment]
No problem, keep making/sharing awesome stuff! 👍

**Pull request merged**
